program: exp.run_mol_exp
command:
  - ${interpreter}
  - "-m"
  - ${program}
  - ${args_hyphens_no_equals} # args
  - "--use_edge_features"
  - "--dump_curves"
method: random
parameters:
  device:
    value: 0
  start_seed:
    value: 0
  stop_seed:
    value: 9
  exp_name:
    value: cwn-molhiv
  indrop_rate:
    value: 0.0
  drop_rate:
    value: 0.5
  graph_norm:
    value: bn
  drop_position:
    value: lin2
  nonlinearity:
    value: relu
  use_coboundaries:
    value: True
  readout:
    value: mean
  final_readout:
    value: sum
  lr:
    value: 0.001
  lr_scheduler:
    value: None
  num_layers:
    value: 2
  emb_dim:
    value: 64
  batch_size:
    value: 128
  epochs:
    value: 150
  num_workers:
    value: 2
  preproc_jobs:
    value: 32
  task_type:
    value: bin_classification
  eval_metric:
    value: ogbg-molhiv
  max_dim:
    value: 2
  max_ring_size:
    value: 6
  init_method:
    value: sum
  train_eval_period:
    value: 10